### ISSUE TITLE
Share a directory from host machine to vm

### ISSUE THREAD

**Issue by chkumar246** [giovtorres/kvm-install-vm#12]
In vagrant, we share a directory from host machine to virtual machine using rsync or sshfs. What is the way to enable the same functionality here.

**Comment by giovtorres** [comment]
Hi @chkumar246, you could also use sshfs or just plain old NFS between the host and the guest.  Both those options would continue to work.

One option I just saw was the [9p fuse filesystem](http://www.linux-kvm.org/page/9p_virtio) using filesystem passthrough.  I'll need to investigate this.

**Comment by giovtorres** [comment]
Closing. This would be a great feature to contribute.
