### ISSUE TITLE
No need to remove cloud-init

### ISSUE THREAD

**Issue by haphan** [giovtorres/kvm-install-vm#15]
Instead of remove cloud-init, what about disable the cloud-init service only @giovtorres ?

Something like 
```
ln-sf /dev/null /etc/systemd/system/cloud-init.service
#or
systemctl disable cloud-init
```

**Comment by giovtorres** [comment]
Hi @haphan, what would be your use case for keeping cloud-init around?

**Comment by haphan** [comment]
The goal of removing cloud init here, as I see it, is to be compatible with
virtual env where cloud init server is unavailable.

To this end, simply disable the sevice is enough. By doing so, it allows
compatibility if moving to the cloud is needed.

Red hat offficial document also suggests to disable cloud init service when
using cloud rhel qcow2 in kvm host.

**Comment by giovtorres** [comment]
I don't see a problem disabling it.  Would you point me to that redhat doc?

**Comment by haphan** [comment]
@giovtorres  https://access.redhat.com/solutions/641193
