### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leifmadsen** [giovtorres/kvm-install-vm#18]
Could a generous license (Apache v2?) be applied to this code base (and ultimately noted as the same license on the source blog article as sourced here: http://giovannitorres.me/create-a-linux-lab-on-kvm-using-cloud-images.html)?

Reason for asking is I'd like to utilize this in my own open source project in good faith.

**Comment by dougbtv** [comment]
+1, I would also like the same! Thanks @giovtorres

**Comment by giovtorres** [comment]
I attached the MIT license (eb82503).
