### ISSUE TITLE
ubuntu1804 cannot boot

### ISSUE THREAD

**Issue by mikemunger** [giovtorres/kvm-install-vm#20]
Hello there, 

The ubuntu1804 image does not seem to work. I think it's because the downloaded image is not a drop-in replacement for ubuntu1604. I'm not quite familiar enough with all this to fix - as I attempted to work toward a pull request a few months ago, but ran into this issue (the image for 1804 has extra partitions I think compared to 1604?)

Here is creating a new machine:
```
$ ./kvm-install-vm create -c 2 -m 2048 -d 10 -t ubuntu1804 -T UTC u1804-test1
- Copying cloud image (ubuntu-18.04-server-cloudimg-amd64.img) ... OK
- Resizing the disk to 10G ... OK
- Generating ISO for cloud-init ... OK
- Creating storage pool ... OK
- Installing the domain ... OK
- Enabling autostart ... OK
- Cleaning up cloud-init files ... OK
- Waiting for domain to get an IP address ... 
```
This where the failure occurs because the machine cannot boot, here is the console output from the machine:
```
Booting from Hard Disk...
error: unknown filesystem.
Entering rescue mode...
grub rescue>
```
I will attempt to add more info in an edit, looking at the u1604 vs u1804 images being used.

Thanks!

**Comment by giovtorres** [comment]
Looks like Ubuntu 1804 doesn't like to be resized.  It works with the default disk size.  I'll have to take a closer look.

**Comment by mikemunger** [comment]
Thanks for your quick response!

I didn't even think to try without specifying disk size as it's my normal process, but that is a good work-around until resizing is addressed.

Thank you

**Comment by giovtorres** [comment]
Unfortunately, the default disk size for ubuntu is 2GB, so you won't be able to do too much without running out of disk space.

It appears this issue may have something to do with virt-resize and EFI guests.  I see a `/boot/efi` partition in 18.04, but not 16.04.

I'll keep looking

**Comment by brianpcurran** [comment]
For what it's worth I installed e2fsprogs 1.44.4 from source on CentOS 7.5, resized an Ubuntu 18.04 disk, and am now getting the same error on the console as the first post on this issue 🙁.

**Comment by brianpcurran** [comment]
@giovtorres You probably already found this bug but it appears to be relevant: https://bugzilla.redhat.com/show_bug.cgi?id=1472039

I've been trying to think of good workarounds to this and haven't come up with anything.

**Comment by brianmutualaid** [comment]
For what it's worth I installed e2fsprogs 1.44.4 from source on CentOS 7.5, resized an Ubuntu 18.04 disk, and am now getting the same error on the console as the first post on this issue 🙁.

**Comment by brianmutualaid** [comment]
@giovtorres You probably already found this bug but it appears to be relevant: https://bugzilla.redhat.com/show_bug.cgi?id=1472039

I've been trying to think of good workarounds to this and haven't come up with anything.

**Comment by brianmutualaid** [comment]
Just opened a pull request that will skip using virt-resize for ubuntu1804 and just use qemu-img to resize. Ubuntu then automatically grows the partition on first boot. This seems like the best workaround given the issues with virt-resize and the Ubuntu 18 cloud image's partition numbering detailed in that bug.

https://github.com/giovtorres/kvm-install-vm/pull/23

**Comment by giovtorres** [comment]
Thanks @brianmutualaid, when I was searching, I don't think I came across that bug.  Thank you for fixing this.  I don't know why Ubuntu has to try so hard to be different, sigh :disappointed:
