### ISSUE TITLE
Beyond spinning up

### ISSUE THREAD

**Issue by sosiouxme** [giovtorres/kvm-install-vm#3]
Thanks for this tool, it seems pretty handy.

I'm not that familiar with using kvm, qemu, and virsh. On Fedora 26 I'm used to having VMs show up in virt-manager for an easy GUI experience. Do you know a way to get VMs created by this tool to show up there?

Also, I'm finding that after shutting them down, when I restart them (virsh start) they don't seem to come up successfully. I can't connect to them via ssh, though a screenshot doesn't show any obvious problems. If they came up with a different IP I'm not sure how to find out what that is. Any advice you can offer?

**Comment by giovtorres** [comment]
Yes, they can show up in the virt-manager gui.  In virt-manager, go to **File -> Add Connection**.  Under the Hypervisor drop-down, select **QEMU/KVM user session** to make a connection to qemu:///session.  You should now see a list of VMs created with this tool.

![selection_068](https://user-images.githubusercontent.com/4281845/31736540-1371190c-b413-11e7-9824-0dcae4995ff0.png)

The second problem is slightly trickier.  I suspect, as you have, that DHCP is supplying a new address.  The manual way of getting the new IP is to check the dnsmasq leases file (`/var/lib/libvirt/dnsmasq/virbr0.status`) for the new IP.  But if there are several entries in there, you'll have to guess until you get it right.  Sometimes the hostname will be in there if the dhcp client in the guest VM sends a hostname.

On the other hand, you could try installing `libvirt-nss`, which would let you reference the guests by name and not IP address.  I have some info on this in the README.  This would be the easier route.

**Comment by sosiouxme** [comment]
Thanks for the rapid response! I did not know about the user session versus the system session, so now I can view VMs in virt-manager fine, thanks.

I would actually like to be referencing by name and not IP, so I installed `libvirt-nss` and configured it as indicated. It didn't work right away, however after rebooting due to other issues I find that resolution does work for the two VMs I created previously, and not the ones I create now. I'm guessing the information from `dnsmasq` is the reason; it looks like this:

```
[
  {
    "ip-address": "192.168.122.125",
    "mac-address": "52:54:00:d3:10:f7",
    "expiry-time": 1508354611
  },
  {
    "ip-address": "192.168.122.54",
    "mac-address": "52:54:00:20:7f:86",
    "hostname": "origin-node-1",
    "expiry-time": 1508355368
  },
  {
    "ip-address": "192.168.122.143",
    "mac-address": "52:54:00:10:79:4e",
    "expiry-time": 1508356266
  },
  {
    "ip-address": "192.168.122.167",
    "mac-address": "52:54:00:2f:c7:ed",
    "expiry-time": 1508356289
  },
  {
    "ip-address": "192.168.122.156",
    "mac-address": "52:54:00:ca:c1:41",
    "hostname": "origin-master",
    "expiry-time": 1508357154
  }
]
```

The ones that have hostnames here resolve... the other ones don't. Not sure what the difference is; they were all created the same way.

**Comment by giovtorres** [comment]
Yes, I made this change recently to the cloud-init config inside the script to restart the networking so that the dhcp client sends the hostname.  If you restarted those VMs whose hostnames aren't present in the dhcp leases file, or just restart the networking service inside those VMs, that would trigger them to show up.  You can verify by running: `sudo virsh net-dhcp-leases default`

```
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2017-10-18 16:17:57  52:54:00:af:68:3f  ipv4      192.168.122.175/24        cobbler         -
```
I'm still tinkering with this a bit...

**Comment by sosiouxme** [comment]
Ah, so if I ssh into the VM, install NetworkManager and start it, then the name shows up and I can use it. So that works fine.

Would be nice if the CentOS cloud images came with that by default :)

Thanks!
