### ISSUE TITLE
Could not resize disk

### ISSUE THREAD

**Issue by tsmilam** [giovtorres/kvm-install-vm#5]
I'll try and figure this out myself, but I was wondering if you've encountered an issue with a failure on disk resizing? Here's what I'm seeing:
```
./kvm-install-vm create ovirtnode2
- Copying cloud image (CentOS-7-x86_64-GenericCloud.qcow2) ... OK
- Resizing the disk to 50 ... ERR: Could not resize disk.
```
The logfile shows this:
```
Formatting 'ovirtnode2.qcow2.new', fmt=qcow2 size=50 cluster_size=65536 preallocation=metadata lazy_refcounts=off refcount_bits=16
virt-resize: error: ovirtnode2.qcow2.new: file is too small to be a disk 
image (512 bytes)

If reporting bugs, run virt-resize with debugging enabled and include the 
complete output:

  virt-resize -v -x [...]
```

**Comment by tsmilam** [comment]
Figured out what the problem was! I had **DISK_SIZE=50** in my ~/.kivrc. It should have read **DISK_SIZE=50G**

**Comment by giovtorres** [comment]
Thanks for pointing this out.  I add the "G" in the script, but forgot it'll need to be there in `.kivrc`.  I'll update it.

**Comment by giovtorres** [comment]
I made some changes in cb994e6, so you don't need to add a `G` in the `.kivrc` file.  I prefer it that way so that both the command line option and the rcfile option are similar in that they both don't need a `G`.
