### ISSUE TITLE
vm hostname cant be resolved

### ISSUE THREAD

**Issue by gwanii** [giovtorres/kvm-install-vm#7]
Hi Giovanni,

I have create vm by using command "kvm-install-vm create foo", the vm was created, but the host "foo" cant be extracted:

```
$ ./kvm-install-vm list
 Id    Name                           State
----------------------------------------------------
 6     foo                            running

$ ping foo                                                   
ping: unknown host foo

$cat /etc/nsswitch.conf |grep hosts
hosts:          files libvirt libvirt_guest mdns4_minimal [NOTFOUND=return] dns

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
```

I have set the "hosts" options in file /etc/nsswitch.conf as the guide in README.md .

Thanks,
Ayakashi

**Comment by giovtorres** [comment]
Looks like you may be missing the libvirt nss package.  I did a quick [search ](https://packages.ubuntu.com/search?keywords=libvirt) and it seems the `libnss-libvirt` package is not available until zesty.  You will need the nss plugin in order to resolve guest hostnames.
