### ISSUE TITLE
Disk size default to only 2.1 GB?

### ISSUE THREAD

**Issue by 2devnull** [giovtorres/kvm-install-vm#8]
New install without specifying disk size and I get a ubuntu instance with only 2.1 GB. 

```
Filesystem      Size  Used Avail Use% Mounted on
udev            238M     0  238M   0% /dev
tmpfs            49M  1.9M   47M   4% /run
/dev/vda1       2.1G  1.5G  574M  73% /
tmpfs           245M     0  245M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           245M     0  245M   0% /sys/fs/cgroup
tmpfs            49M     0   49M   0% /run/user/1000
```

**Comment by giovtorres** [comment]
Yes, that is the size of the qcow2 image provided by Ubuntu.
```
$ qemu-img info virt/images/ubuntu-16.04-server-cloudimg-amd64-disk1.img | grep 'virtual size'
virtual size: 2.2G (2361393152 bytes)
```

A suggestion would be to use the `.kivrc` file and set a minimum size that allows you more disk space by default.  Then, you can always override the default in the `.kivrc` file with the `-d` command line flag.

**Comment by 2devnull** [comment]
ok, thanks I did a resize manually following what was in the script. One thing to note is that the script has /dev/sda1 for the resize, but apparently, the cloud image for ubuntu is /dev/vda1

**Comment by giovtorres** [comment]
Thanks, although that doesn't seem to matter and the root partition does resize with the `-d` flag on Ubuntu:

```
$ kvm-install-vm create -d 5 -t ubuntu1604 issue8
...
```
```
$ ssh issue8
...
giovanni@issue8:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       4.8G  855M  4.0G  18% /
```

**Comment by 2devnull** [comment]
interesting...ok, I wasn't using the .kivrc before, so next time I'll do it. Thanks for this script, it makes things very easy.

**Comment by giovtorres** [comment]
Thanks.
